application: belay-station
version: 1
runtime: python
api_version: 1

handlers:

- url: /
  script: station.py

- url: /generate
  script: station.py
  
- url: /data
  script: station.py

- url: /(.*\.(html|css|js|png))
  script: lib/CORSstatic.py

- url: /test
  script: lib/test.py

